project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: ./
preserve_hierarchy: true

files:
  -
    source: /en-GB/**/*.json
    translation: /%two_letters_code%/**/%original_file_name%
    ignore:
      - /*/locale.json
    languages_mapping:
      two_letters_code:
        en-GB: en-GB
        en-US: en-US
        es-ES: es-ES
        pt-BR: pt-BR
        sv-SE: sv-SE
        zh-CN: zh-CN
        zh-TW: zh-TW
